spring.application.name=ms-despacho
server.port=8087

#cambiar parte final del url por cada ms
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/feriando_db?currentSchema=despacho_schema}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:Pipelolaturri2810.}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=despacho_schema
spring.jpa.show-sql=false

logging.level.cl.feriando=INFO
