spring.application.name=ms-producto
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/feriando_db?currentSchema=producto_schema
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=producto_schema
spring.jpa.show-sql=false

logging.level.cl.feriando=INFO
