spring.application.name=ms-calificacion
server.port=8089

spring.datasource.url=jdbc:postgresql://localhost:5432/feriando_db?currentSchema=calificacion_schema
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=calificacion_schema
spring.jpa.show-sql=false

# URL de ms-feriante para actualizar promedio
feriando.ms-feriante.url=http://localhost:8082

logging.level.cl.feriando=INFO
