spring.application.name=ms-feriante
server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/feriando_db?currentSchema=feriante_schema}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:Pipelolaturri2810.}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=feriante_schema
spring.jpa.show-sql=false

# URL del microservicio de usuarios (para validar id_usuario)
feriando.ms-usuario.url=http://localhost:8081

logging.level.cl.feriando=INFO
