spring.application.name=ms-carrito
server.port=8085

#cambiar parte final del url por cada ms
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/feriando_db?currentSchema=carrito_schema}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:Pipelolaturri2810.}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=carrito_schema
spring.jpa.show-sql=false

# URL de ms-producto (para validar el id_producto y leer precio)
feriando.ms-producto.url=http://localhost:8083

logging.level.cl.feriando=INFO
