name: Deploy MS Reporte

on:
  push:
    branches:
      - main
    paths:
      - 'ms-reporte/**' #1 cambiar nombre de cada microsrevicio
      - '.github/workflows/deploy-ms-reporte.yml' #2 cambiar el nombre de este archivo

env:
  PROJECT_ID: feriando-499722
  REGION: southamerica-west1
  REPO_NAME: microservicios-feriando
  SERVICE_NAME: ms-reporte #3 cambiar el nombre de tu microservicio


  DB_INSTANCE: feriando-499722:southamerica-west1:feriando

jobs:
  deploy-service:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v3

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Autenticar con Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configurar Docker en la nube
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Compilar Microservicio
        run: mvn clean package -DskipTests
        working-directory: ./${{ env.SERVICE_NAME }}

      - name: Construir y Subir Imagen Docker
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        working-directory: ./${{ env.SERVICE_NAME }}

      - name: Desplegar en Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: '--add-cloudsql-instances=${{ env.DB_INSTANCE }} --allow-unauthenticated'
          env_vars: |-
            DB_URL=jdbc:postgresql:///feriando_db?cloudSqlInstance=${{ env.DB_INSTANCE }}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&currentSchema=reporte_schema
            DB_USER=postgres
            DB_PASS=Pipelolaturri2810.
          #aqui en db url hay que cambiar al final el nombre del schema